spring:
  application:
    name: threat-detection-platform
    
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    
  redis:
    url: ${REDIS_URL}
    
server:
  port: ${PORT:8080}
  
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
        
logging:
  level:
    com.mriridescent.threatdetection: INFO
    
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000
  
demo:
  enabled: true
