name: 🚀 Feature Request
description: Suggest an idea for the threat detection platform
title: '[FEATURE] '
labels: ['enhancement', 'needs-triage']
assignees: ['mriridescent']

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! 🚀
        
        Please provide as much detail as possible to help us understand your request.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - Project Iris (Email Detection)
        - PhishNet Analyst (Campaign Analysis)
        - Agent Coordinator
        - Web Interface
        - API
        - AI/ML Models
        - Deployment/Infrastructure
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New AI/ML Capability
        - User Interface Enhancement
        - API Enhancement
        - Performance Improvement
        - Security Enhancement
        - Integration
        - Documentation
        - Developer Experience
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered.

  - type: textarea
    id: use_cases
    attributes:
      label: Use Cases
      description: Describe specific use cases for this feature
      placeholder: |
        1. As a security analyst, I want to...
        2. As an administrator, I need to...
        3. As a developer, I would like to...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my workflow
        - Critical - Blocking my usage
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Low - Simple change or addition
        - Medium - Moderate development effort
        - High - Significant development effort
        - Very High - Major architectural changes
        - Unknown

  - type: textarea
    id: technical_details
    attributes:
      label: Technical Details
      description: Any technical considerations or implementation details
      placeholder: |
        - API endpoints needed
        - Database changes required
        - UI/UX considerations
        - Performance implications
        - Security considerations

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: If applicable, add mockups, wireframes, or examples
      placeholder: Drag and drop images here or provide links to examples...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Any additional information that might be helpful...

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided a clear problem statement and solution
          required: true
        - label: I have considered alternative solutions
          required: true
        - label: I have described specific use cases
          required: true
